### ISSUE TITLE
Why so many versions of opencv

### ISSUE THREAD

**Issue by ruze00** [Dipeshpal/Jarvis_AI#20]
I don't understand what this is trying to do.  Why are so many versions of OpenCV being installed?  Why is OpenCV an imaging toolkit needed for speech processing?

![image](https://user-images.githubusercontent.com/3300000/181741597-26315d91-78cc-4507-b02d-b9503e13aa23.png)

Also there are a couple different versions of numpy being installed.

Finally, do you know Jarvis is a registered trademark for NVidia voice assistant? 😆

**Comment by Dipeshpal** [comment]
By default, it just downloads the latest version of OpenCV, but because of dependencies, it might require some other versions.

I know Jarvis is NVidia's registered trademark, which is why this one is known as JarvisAI and it is an entirely open source project.
