### ISSUE TITLE
Simple AI reply

### ISSUE THREAD

**Issue by Hunter2807** [Dipeshpal/Jarvis_AI#8]
Hey! 

I like your project, but I wanna implement this into a discord bot, and I want the module to answer to a text message. Is there any method like, `reply = ai.get_ai_reply('Hey')`. 

And also, it would be great if you get some docs for the same! 

But it would be great if you help me so that it can also answer by text questions. And also, is there an async version? 

Thank you in advance

**Comment by Dipeshpal** [comment]
Currently it doesn't have that functionality. I would recommend you to read library docs and check example. Watch my youtube videos you will understand.

This might help you- https://jarvis-ai-api.herokuapp.com/documents/
